version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: commander
    versions:
    - 6.2.0
    - 7.1.0
  - dependency-name: "@types/react"
    versions:
    - 17.0.0
    - 17.0.1
    - 17.0.2
  - dependency-name: lodash-es
    versions:
    - 4.17.20
  - dependency-name: yup
    versions:
    - 0.32.8
  - dependency-name: semantic-ui-react
    versions:
    - 2.0.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
